apiVersion: apps/v1
kind: Deployment
metadata:
  name: andersen-professional-react
  labels:
    app: andersen-professional
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andersen-professional
  template:
    metadata:
      labels:
        app: andersen-professional
    spec:
      containers:
      - name: andersen-professional-react
        image: mandersen1208/andersen-professional-react:latest
----
appversion: v1
kind: Service
metadata:
  name: andersen-professional-react
  labels:
    app: andersen-professional
spec:
  type: NodePort
  selector:
    app: andersen-professional
  ports:
  - name: andersen-professional-react
    port: 3000  
    targetPort: 3000
